name: Release Verify
permissions:
  "contents": "read"

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-local-artifacts:
    name: build-local-artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: 'ubuntu-24.04'
            container: 'buildpack-deps:focal'
            target: 'x86_64-unknown-linux-gnu'
          - runner: 'macos-15-intel'
            target: 'x86_64-apple-darwin'
          - runner: 'macos-14'
            target: 'aarch64-apple-darwin'
          - runner: 'windows-2022'
            target: 'x86_64-pc-windows-msvc'
    runs-on: ${{ matrix.runner }}
    container: ${{ matrix.container }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: astral-sh/setup-uv@v6
      - name: Install jq
        if: matrix.container == 'buildpack-deps:focal'
        run: curl -o /usr/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/bin/jq
      - uses: Swatinem/rust-cache@v2.7.3
      - name: Install dll-pack-builder
        run: uv tool install git+https://github.com/foro-fmt/dll-pack-builder@1e90b63
      - name: Build artifacts
        env:
          DLL_PACK_TARGET: ${{ matrix.target }}
          BUILD_OUT_DIR: ./target/${{ matrix.target }}/super-release
          DLL_PACK_GH_TAG: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
        run: bash ./dll-pack-build-local.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-build-local-${{ matrix.target }}
          path: artifacts

  build-global-artifacts:
    needs:
      - build-local-artifacts
    runs-on: "ubuntu-latest"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dll-pack-builder
        run: python3 -m pip install git+https://github.com/foro-fmt/dll-pack-builder@1e90b63
      - name: Fetch local artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          path: artifacts
          merge-multiple: true
      - name: Build artifacts
        run: bash ./dll-pack-build-global.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-build-global
          path: artifacts
